# Generated by Django 5.2.1 on 2025-06-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtube_playlist_url',
            field=models.URLField(blank=True, help_text='Paste a YouTube playlist URL here.', null=True),
        ),
    ]
