# Generated by Django 5.2.1 on 2025-06-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_videoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoprogress',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
